# For Research Paper - Visualisations

## Random Viz 

- Creating Barplots based on 20 random sets for N = 6 -- **autmated**
- I think easiest is non-elegant to add it to basic 2 socio-dem. graphs

In [64]:
random_df = pd.read_csv('data/temp/random_vehicles_N6_S20_test.csv')

#### Here we round them to 1 decomal place, can be changed to 2 if needed for Eucelidean distance and %

In [65]:
# Convert all numeric values (ignore non-numeric) and round to 1 decimal
random_df = random_df.apply(pd.to_numeric, errors='coerce')
random_df[random_df.columns] = random_df.round(1)

#### This may work as well or pivoted in the next step

In [66]:
random_df

,random_1,random_2,random_3,random_4,random_5,random_6,random_7,random_8,random_9,random_10,...,random_13,random_14,random_15,random_16,random_17,random_18,random_19,random_20,all_vehicles,Amsterdam
A_inhab,180070.0,197970.0,267175.0,199900.0,159635.0,163950.0,236195.0,157450.0,211075.0,147070.0,...,251425.0,131760.0,215025.0,175055.0,108910.0,268845.0,173215.0,258390.0,8471845.0,NaN
A_0_15,21732.0,23966.0,32015.0,23063.0,18526.0,19722.0,28767.0,19512.0,25007.0,18747.0,...,32795.0,14922.0,29575.0,22009.0,12965.0,33562.0,19851.0,30769.0,1050147.0,NaN
A_65+,23705.0,22187.0,31560.0,26161.0,19285.0,20951.0,29696.0,19028.0,25306.0,20557.0,...,26883.0,15934.0,27251.0,21542.0,14195.0,32016.0,22203.0,33591.0,1047752.0,NaN
A_nederlan,66603.0,85384.0,107494.0,92507.0,69638.0,76213.0,95027.0,60750.0,96757.0,63650.0,...,101531.0,57267.0,95044.0,79701.0,51909.0,107080.0,76042.0,113217.0,3656741.0,NaN
A_n_west_m,76680.0,69326.0,105072.0,61295.0,55331.0,48933.0,88830.0,65273.0,66858.0,52133.0,...,100317.0,45190.0,79315.0,56183.0,33207.0,105482.0,59107.0,87997.0,3006099.0,NaN
count,41801.0,50001.0,49830.0,54087.0,52233.0,49062.0,44160.0,42030.0,50799.0,53892.0,...,46059.0,41896.0,55431.0,46552.0,38776.0,30006.0,59711.0,48764.0,2127870.0,NaN
A_inhab_uniq,119810.0,162325.0,193700.0,115525.0,130430.0,116795.0,165140.0,133665.0,173735.0,130915.0,...,143385.0,112965.0,181615.0,156760.0,102390.0,196425.0,96840.0,164435.0,403240.0,870375.0
A_0_15_uniq,13980.0,20231.0,23833.0,13373.0,15526.0,14946.0,20515.0,16814.0,21135.0,16816.0,...,18229.0,12827.0,24865.0,20210.0,12118.0,24617.0,11690.0,19832.0,52298.0,122388.0
A_65+_uniq,16159.0,18117.0,22945.0,15182.0,15614.0,14737.0,20941.0,16382.0,20804.0,18025.0,...,16014.0,13756.0,22647.0,19376.0,13465.0,24419.0,12505.0,21635.0,51191.0,112084.0
A_nederlan_uniq,49546.0,68508.0,78062.0,54488.0,57080.0,52677.0,66317.0,53519.0,78808.0,55567.0,...,59703.0,49389.0,81146.0,70322.0,49462.0,80865.0,41961.0,70745.0,178541.0,382106.0
A_n_west_m_uniq,43184.0,59117.0,75837.0,34379.0,45238.0,38369.0,63359.0,52818.0,56557.0,48074.0,...,54786.0,38776.0,65040.0,51807.0,30576.0,74626.0,34696.0,57971.0,141092.0,315614.0
cells_unique,937.0,991.0,1294.0,778.0,926.0,830.0,1210.0,977.0,1108.0,1096.0,...,925.0,753.0,1286.0,1094.0,781.0,1374.0,688.0,1200.0,2915.0,6906.0
G_woz_woni,446.1,438.9,426.6,471.0,467.0,505.8,459.2,407.7,493.4,484.9,...,404.1,446.9,460.9,475.2,458.9,412.2,439.1,416.7,452.3,469.2
dutch_share_pct,41.4,42.2,40.3,47.2,43.8,45.1,40.2,40.0,45.4,42.4,...,41.6,43.7,44.7,44.9,48.3,41.2,43.3,43.0,44.3,43.9
non_western_share_pct,36.0,36.4,39.2,29.8,34.7,32.8,38.4,39.5,32.6,36.7,...,38.2,34.3,35.8,33.0,29.9,38.0,35.8,35.2,35.0,36.3
young_share_pct,11.7,12.5,12.3,11.6,11.9,12.8,12.4,12.6,12.2,12.8,...,12.7,11.4,13.7,12.9,11.8,12.5,12.1,12.1,13.0,14.1
old_share_pct,13.5,11.2,11.8,13.1,12.0,12.6,12.7,12.3,12.0,13.8,...,11.2,12.2,12.5,12.4,13.2,12.4,12.9,13.2,12.7,12.9
euclidean_distance,23.4,30.5,42.9,7.9,3.6,36.8,11.0,61.7,24.6,15.8,...,65.2,22.5,8.4,7.0,13.1,57.2,30.2,52.6,17.0,0.0
buses_count,4.0,2.0,3.0,2.0,3.0,1.0,3.0,4.0,3.0,3.0,...,5.0,2.0,5.0,3.0,2.0,6.0,2.0,6.0,145.0,NaN
trams_count,2.0,4.0,3.0,4.0,3.0,5.0,3.0,2.0,3.0,3.0,...,1.0,4.0,1.0,3.0,4.0,0.0,4.0,0.0,133.0,NaN
routes_unique,10.0,11.0,11.0,6.0,8.0,6.0,9.0,9.0,10.0,10.0,...,8.0,8.0,11.0,9.0,6.0,12.0,6.0,9.0,54.0,NaN
avg_points_per_cell,44.6,50.5,38.5,69.5,56.4,59.1,36.5,43.0,45.8,49.2,...,49.8,55.6,43.1,42.6,49.6,21.8,86.8,40.6,730.0,NaN

#### PIVOTED!

In [67]:
random_df = random_df.T

In [68]:
random_df

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
random_1,180070.0,21732.0,23705.0,66603.0,76680.0,41801.0,119810.0,13980.0,16159.0,49546.0,...,446.1,41.4,36.0,11.7,13.5,23.4,4.0,2.0,10.0,44.6
random_2,197970.0,23966.0,22187.0,85384.0,69326.0,50001.0,162325.0,20231.0,18117.0,68508.0,...,438.9,42.2,36.4,12.5,11.2,30.5,2.0,4.0,11.0,50.5
random_3,267175.0,32015.0,31560.0,107494.0,105072.0,49830.0,193700.0,23833.0,22945.0,78062.0,...,426.6,40.3,39.2,12.3,11.8,42.9,3.0,3.0,11.0,38.5
random_4,199900.0,23063.0,26161.0,92507.0,61295.0,54087.0,115525.0,13373.0,15182.0,54488.0,...,471.0,47.2,29.8,11.6,13.1,7.9,2.0,4.0,6.0,69.5
random_5,159635.0,18526.0,19285.0,69638.0,55331.0,52233.0,130430.0,15526.0,15614.0,57080.0,...,467.0,43.8,34.7,11.9,12.0,3.6,3.0,3.0,8.0,56.4
random_6,163950.0,19722.0,20951.0,76213.0,48933.0,49062.0,116795.0,14946.0,14737.0,52677.0,...,505.8,45.1,32.8,12.8,12.6,36.8,1.0,5.0,6.0,59.1
random_7,236195.0,28767.0,29696.0,95027.0,88830.0,44160.0,165140.0,20515.0,20941.0,66317.0,...,459.2,40.2,38.4,12.4,12.7,11.0,3.0,3.0,9.0,36.5
random_8,157450.0,19512.0,19028.0,60750.0,65273.0,42030.0,133665.0,16814.0,16382.0,53519.0,...,407.7,40.0,39.5,12.6,12.3,61.7,4.0,2.0,9.0,43.0
random_9,211075.0,25007.0,25306.0,96757.0,66858.0,50799.0,173735.0,21135.0,20804.0,78808.0,...,493.4,45.4,32.6,12.2,12.0,24.6,3.0,3.0,10.0,45.8
random_10,147070.0,18747.0,20557.0,63650.0,52133.0,53892.0,130915.0,16816.0,18025.0,55567.0,...,484.9,42.4,36.7,12.8,13.8,15.8,3.0,3.0,10.0,49.2
random_11,174265.0,20811.0,21062.0,76739.0,59492.0,42810.0,153925.0,18554.0,18567.0,67684.0,...,433.1,44.0,34.0,12.0,12.1,36.2,3.0,3.0,9.0,39.4
random_12,205935.0,25207.0,24522.0,95275.0,66591.0,55408.0,177310.0,21892.0,21278.0,81924.0,...,492.0,46.2,32.2,12.4,12.0,23.3,3.0,3.0,9.0,49.6
random_13,251425.0,32795.0,26883.0,101531.0,100317.0,46059.0,143385.0,18229.0,16014.0,59703.0,...,404.1,41.6,38.2,12.7,11.2,65.2,5.0,1.0,8.0,49.8
random_14,131760.0,14922.0,15934.0,57267.0,45190.0,41896.0,112965.0,12827.0,13756.0,49389.0,...,446.9,43.7,34.3,11.4,12.2,22.5,2.0,4.0,8.0,55.6
random_15,215025.0,29575.0,27251.0,95044.0,79315.0,55431.0,181615.0,24865.0,22647.0,81146.0,...,460.9,44.7,35.8,13.7,12.5,8.4,5.0,1.0,11.0,43.1
random_16,175055.0,22009.0,21542.0,79701.0,56183.0,46552.0,156760.0,20210.0,19376.0,70322.0,...,475.2,44.9,33.0,12.9,12.4,7.0,3.0,3.0,9.0,42.6
random_17,108910.0,12965.0,14195.0,51909.0,33207.0,38776.0,102390.0,12118.0,13465.0,49462.0,...,458.9,48.3,29.9,11.8,13.2,13.1,2.0,4.0,6.0,49.6
random_18,268845.0,33562.0,32016.0,107080.0,105482.0,30006.0,196425.0,24617.0,24419.0,80865.0,...,412.2,41.2,38.0,12.5,12.4,57.2,6.0,0.0,12.0,21.8
random_19,173215.0,19851.0,22203.0,76042.0,59107.0,59711.0,96840.0,11690.0,12505.0,41961.0,...,439.1,43.3,35.8,12.1,12.9,30.2,2.0,4.0,6.0,86.8
random_20,258390.0,30769.0,33591.0,113217.0,87997.0,48764.0,164435.0,19832.0,21635.0,70745.0,...,416.7,43.0,35.2,12.1,13.2,52.6,6.0,0.0,9.0,40.6
all_vehicles,8471845.0,1050147.0,1047752.0,3656741.0,3006099.0,2127870.0,403240.0,52298.0,51191.0,178541.0,...,452.3,44.3,35.0,13.0,12.7,17.0,145.0,133.0,54.0,730.0
Amsterdam,NaN,NaN,NaN,NaN,NaN,NaN,870375.0,122388.0,112084.0,382106.0,...,469.2,43.9,36.3,14.1,12.9,0.0,NaN,NaN,NaN,NaN

In [69]:
import pandas as pd

In [70]:
random_df = pd.read_csv('data/temp/random_vehicles_N6_S20_test.csv')

#### Here we round them to 1 decomal place, can be changed to 2 if needed for Eucelidean distance and %

In [71]:
# Convert all numeric values (ignore non-numeric) and round to 1 decimal
random_df = random_df.apply(pd.to_numeric, errors='coerce')
random_df[random_df.columns] = random_df.round(1)

#### This may work as well or pivoted in the next step

In [72]:
random_df

,random_1,random_2,random_3,random_4,random_5,random_6,random_7,random_8,random_9,random_10,...,random_13,random_14,random_15,random_16,random_17,random_18,random_19,random_20,all_vehicles,Amsterdam
A_inhab,180070.0,197970.0,267175.0,199900.0,159635.0,163950.0,236195.0,157450.0,211075.0,147070.0,...,251425.0,131760.0,215025.0,175055.0,108910.0,268845.0,173215.0,258390.0,8471845.0,NaN
A_0_15,21732.0,23966.0,32015.0,23063.0,18526.0,19722.0,28767.0,19512.0,25007.0,18747.0,...,32795.0,14922.0,29575.0,22009.0,12965.0,33562.0,19851.0,30769.0,1050147.0,NaN
A_65+,23705.0,22187.0,31560.0,26161.0,19285.0,20951.0,29696.0,19028.0,25306.0,20557.0,...,26883.0,15934.0,27251.0,21542.0,14195.0,32016.0,22203.0,33591.0,1047752.0,NaN
A_nederlan,66603.0,85384.0,107494.0,92507.0,69638.0,76213.0,95027.0,60750.0,96757.0,63650.0,...,101531.0,57267.0,95044.0,79701.0,51909.0,107080.0,76042.0,113217.0,3656741.0,NaN
A_n_west_m,76680.0,69326.0,105072.0,61295.0,55331.0,48933.0,88830.0,65273.0,66858.0,52133.0,...,100317.0,45190.0,79315.0,56183.0,33207.0,105482.0,59107.0,87997.0,3006099.0,NaN
count,41801.0,50001.0,49830.0,54087.0,52233.0,49062.0,44160.0,42030.0,50799.0,53892.0,...,46059.0,41896.0,55431.0,46552.0,38776.0,30006.0,59711.0,48764.0,2127870.0,NaN
A_inhab_uniq,119810.0,162325.0,193700.0,115525.0,130430.0,116795.0,165140.0,133665.0,173735.0,130915.0,...,143385.0,112965.0,181615.0,156760.0,102390.0,196425.0,96840.0,164435.0,403240.0,870375.0
A_0_15_uniq,13980.0,20231.0,23833.0,13373.0,15526.0,14946.0,20515.0,16814.0,21135.0,16816.0,...,18229.0,12827.0,24865.0,20210.0,12118.0,24617.0,11690.0,19832.0,52298.0,122388.0
A_65+_uniq,16159.0,18117.0,22945.0,15182.0,15614.0,14737.0,20941.0,16382.0,20804.0,18025.0,...,16014.0,13756.0,22647.0,19376.0,13465.0,24419.0,12505.0,21635.0,51191.0,112084.0
A_nederlan_uniq,49546.0,68508.0,78062.0,54488.0,57080.0,52677.0,66317.0,53519.0,78808.0,55567.0,...,59703.0,49389.0,81146.0,70322.0,49462.0,80865.0,41961.0,70745.0,178541.0,382106.0
A_n_west_m_uniq,43184.0,59117.0,75837.0,34379.0,45238.0,38369.0,63359.0,52818.0,56557.0,48074.0,...,54786.0,38776.0,65040.0,51807.0,30576.0,74626.0,34696.0,57971.0,141092.0,315614.0
cells_unique,937.0,991.0,1294.0,778.0,926.0,830.0,1210.0,977.0,1108.0,1096.0,...,925.0,753.0,1286.0,1094.0,781.0,1374.0,688.0,1200.0,2915.0,6906.0
G_woz_woni,446.1,438.9,426.6,471.0,467.0,505.8,459.2,407.7,493.4,484.9,...,404.1,446.9,460.9,475.2,458.9,412.2,439.1,416.7,452.3,469.2
dutch_share_pct,41.4,42.2,40.3,47.2,43.8,45.1,40.2,40.0,45.4,42.4,...,41.6,43.7,44.7,44.9,48.3,41.2,43.3,43.0,44.3,43.9
non_western_share_pct,36.0,36.4,39.2,29.8,34.7,32.8,38.4,39.5,32.6,36.7,...,38.2,34.3,35.8,33.0,29.9,38.0,35.8,35.2,35.0,36.3
young_share_pct,11.7,12.5,12.3,11.6,11.9,12.8,12.4,12.6,12.2,12.8,...,12.7,11.4,13.7,12.9,11.8,12.5,12.1,12.1,13.0,14.1
old_share_pct,13.5,11.2,11.8,13.1,12.0,12.6,12.7,12.3,12.0,13.8,...,11.2,12.2,12.5,12.4,13.2,12.4,12.9,13.2,12.7,12.9
euclidean_distance,23.4,30.5,42.9,7.9,3.6,36.8,11.0,61.7,24.6,15.8,...,65.2,22.5,8.4,7.0,13.1,57.2,30.2,52.6,17.0,0.0
buses_count,4.0,2.0,3.0,2.0,3.0,1.0,3.0,4.0,3.0,3.0,...,5.0,2.0,5.0,3.0,2.0,6.0,2.0,6.0,145.0,NaN
trams_count,2.0,4.0,3.0,4.0,3.0,5.0,3.0,2.0,3.0,3.0,...,1.0,4.0,1.0,3.0,4.0,0.0,4.0,0.0,133.0,NaN
routes_unique,10.0,11.0,11.0,6.0,8.0,6.0,9.0,9.0,10.0,10.0,...,8.0,8.0,11.0,9.0,6.0,12.0,6.0,9.0,54.0,NaN
avg_points_per_cell,44.6,50.5,38.5,69.5,56.4,59.1,36.5,43.0,45.8,49.2,...,49.8,55.6,43.1,42.6,49.6,21.8,86.8,40.6,730.0,NaN

#### PIVOTED!

In [73]:
random_df = random_df.T

In [74]:
random_df

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
random_1,180070.0,21732.0,23705.0,66603.0,76680.0,41801.0,119810.0,13980.0,16159.0,49546.0,...,446.1,41.4,36.0,11.7,13.5,23.4,4.0,2.0,10.0,44.6
random_2,197970.0,23966.0,22187.0,85384.0,69326.0,50001.0,162325.0,20231.0,18117.0,68508.0,...,438.9,42.2,36.4,12.5,11.2,30.5,2.0,4.0,11.0,50.5
random_3,267175.0,32015.0,31560.0,107494.0,105072.0,49830.0,193700.0,23833.0,22945.0,78062.0,...,426.6,40.3,39.2,12.3,11.8,42.9,3.0,3.0,11.0,38.5
random_4,199900.0,23063.0,26161.0,92507.0,61295.0,54087.0,115525.0,13373.0,15182.0,54488.0,...,471.0,47.2,29.8,11.6,13.1,7.9,2.0,4.0,6.0,69.5
random_5,159635.0,18526.0,19285.0,69638.0,55331.0,52233.0,130430.0,15526.0,15614.0,57080.0,...,467.0,43.8,34.7,11.9,12.0,3.6,3.0,3.0,8.0,56.4
random_6,163950.0,19722.0,20951.0,76213.0,48933.0,49062.0,116795.0,14946.0,14737.0,52677.0,...,505.8,45.1,32.8,12.8,12.6,36.8,1.0,5.0,6.0,59.1
random_7,236195.0,28767.0,29696.0,95027.0,88830.0,44160.0,165140.0,20515.0,20941.0,66317.0,...,459.2,40.2,38.4,12.4,12.7,11.0,3.0,3.0,9.0,36.5
random_8,157450.0,19512.0,19028.0,60750.0,65273.0,42030.0,133665.0,16814.0,16382.0,53519.0,...,407.7,40.0,39.5,12.6,12.3,61.7,4.0,2.0,9.0,43.0
random_9,211075.0,25007.0,25306.0,96757.0,66858.0,50799.0,173735.0,21135.0,20804.0,78808.0,...,493.4,45.4,32.6,12.2,12.0,24.6,3.0,3.0,10.0,45.8
random_10,147070.0,18747.0,20557.0,63650.0,52133.0,53892.0,130915.0,16816.0,18025.0,55567.0,...,484.9,42.4,36.7,12.8,13.8,15.8,3.0,3.0,10.0,49.2
random_11,174265.0,20811.0,21062.0,76739.0,59492.0,42810.0,153925.0,18554.0,18567.0,67684.0,...,433.1,44.0,34.0,12.0,12.1,36.2,3.0,3.0,9.0,39.4
random_12,205935.0,25207.0,24522.0,95275.0,66591.0,55408.0,177310.0,21892.0,21278.0,81924.0,...,492.0,46.2,32.2,12.4,12.0,23.3,3.0,3.0,9.0,49.6
random_13,251425.0,32795.0,26883.0,101531.0,100317.0,46059.0,143385.0,18229.0,16014.0,59703.0,...,404.1,41.6,38.2,12.7,11.2,65.2,5.0,1.0,8.0,49.8
random_14,131760.0,14922.0,15934.0,57267.0,45190.0,41896.0,112965.0,12827.0,13756.0,49389.0,...,446.9,43.7,34.3,11.4,12.2,22.5,2.0,4.0,8.0,55.6
random_15,215025.0,29575.0,27251.0,95044.0,79315.0,55431.0,181615.0,24865.0,22647.0,81146.0,...,460.9,44.7,35.8,13.7,12.5,8.4,5.0,1.0,11.0,43.1
random_16,175055.0,22009.0,21542.0,79701.0,56183.0,46552.0,156760.0,20210.0,19376.0,70322.0,...,475.2,44.9,33.0,12.9,12.4,7.0,3.0,3.0,9.0,42.6
random_17,108910.0,12965.0,14195.0,51909.0,33207.0,38776.0,102390.0,12118.0,13465.0,49462.0,...,458.9,48.3,29.9,11.8,13.2,13.1,2.0,4.0,6.0,49.6
random_18,268845.0,33562.0,32016.0,107080.0,105482.0,30006.0,196425.0,24617.0,24419.0,80865.0,...,412.2,41.2,38.0,12.5,12.4,57.2,6.0,0.0,12.0,21.8
random_19,173215.0,19851.0,22203.0,76042.0,59107.0,59711.0,96840.0,11690.0,12505.0,41961.0,...,439.1,43.3,35.8,12.1,12.9,30.2,2.0,4.0,6.0,86.8
random_20,258390.0,30769.0,33591.0,113217.0,87997.0,48764.0,164435.0,19832.0,21635.0,70745.0,...,416.7,43.0,35.2,12.1,13.2,52.6,6.0,0.0,9.0,40.6
all_vehicles,8471845.0,1050147.0,1047752.0,3656741.0,3006099.0,2127870.0,403240.0,52298.0,51191.0,178541.0,...,452.3,44.3,35.0,13.0,12.7,17.0,145.0,133.0,54.0,730.0
Amsterdam,NaN,NaN,NaN,NaN,NaN,NaN,870375.0,122388.0,112084.0,382106.0,...,469.2,43.9,36.3,14.1,12.9,0.0,NaN,NaN,NaN,NaN

## 3 Main Optmizaitions (Spatial, Temporal, Fair)

- Create **3 MAIN viz – spatial, temporal, fair** - 
- Create DF for 3 MAIN viz (temporal, spatial, fair) + with all values – for N=6, N=10, N=20, N=30, N=40, N=50, N=100 N=All? 
- Spatial (unique cells) / Temporal (avg points per uniq. cells) X - Y + color = Fairness (Euclidean distance) + size = N 
- N = calcualted as sum of buses + trams 
- Relative used even if sometimes absolute is a bit bettter (rethink?)
- Temporal optmization starting from max points vehicle and not from max avg measures per uniq (rethink?)
- if needed we can add 60, 70, 80, 90

In [50]:
opti_df_6 = pd.read_csv('data/temp/optimzed_vehicles_N6_test.csv')
opti_df_10 = pd.read_csv('data/temp/optimzed_vehicles_N10_test.csv')
opti_df_20 = pd.read_csv('data/temp/optimzed_vehicles_N20_test.csv')
opti_df_30 = pd.read_csv('data/temp/optimzed_vehicles_N30_test.csv')
opti_df_40 = pd.read_csv('data/temp/optimzed_vehicles_N40_test.csv')
opti_df_50 = pd.read_csv('data/temp/optimzed_vehicles_N50_test.csv')
opti_df_100 = pd.read_csv('data/temp/optimzed_vehicles_N100_test.csv')

In [78]:
vehicles_ams = pd.read_csv('data/temp/all_vehicles_Amsterdam_test.csv')

In [80]:
vehicles_ams = vehicles_ams.T

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
all_vehicles,8471845.0,1050147.0,1047752.0,3656741.0,3006099.0,2127870.0,403240.0,52298.0,51191.0,178541.0,...,452.319784,44.28,34.99,12.97,12.69,16.98,145.0,133.0,54.0,729.97
Amsterdam,-,-,-,-,-,-,870375.0,122388,112084,382106,...,469.21,43.9,36.26,14.06,12.88,0,-,-,-,-

#### Here we round them to 1 decomal place, can be changed to 2 if needed for Eucelidean distance and %

In [51]:
for df_name in ['opti_df_6', 'opti_df_10', 'opti_df_20', 'opti_df_30', 'opti_df_40', 'opti_df_50', 'opti_df_100']:
    df = globals()[df_name]
    df_numeric = df.apply(pd.to_numeric, errors='coerce')
    df[df_numeric.columns] = df_numeric.round(1)

#### This may work as well or pivoted in the next step

#### PIVOTED!

In [52]:
# do pivot for all opti 
opti_df_6 = opti_df_6.T
opti_df_10 = opti_df_10.T
opti_df_20 = opti_df_20.T
opti_df_30 = opti_df_30.T
opti_df_40 = opti_df_40.T
opti_df_50 = opti_df_50.T
opti_df_100 = opti_df_100.T

In [58]:
opti_df_6

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
max_spatial_6,405385.0,51441.0,50666.0,181266.0,137821.0,52292.0,306580.0,39458.0,39063.0,137193.0,...,468.9,44.8,34.3,12.9,12.7,2.5,5.0,1.0,21.0,24.5
max_temporal_6,131775.0,18581.0,19744.0,51782.0,60119.0,50185.0,37635.0,5367.0,5601.0,15644.0,...,382.6,41.6,43.1,14.3,14.9,87.0,6.0,0.0,3.0,170.7
fairest_relative_6,215725.0,25652.0,27096.0,90535.0,78960.0,50534.0,172605.0,20861.0,21613.0,72319.0,...,470.1,41.9,36.7,12.1,12.5,3.0,4.0,2.0,12.0,41.2

In [57]:
opti_df_10

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
max_spatial_10,587505.0,71715.0,72863.0,261317.0,199562.0,95856.0,354185.0,45384.0,44718.0,158150.0,...,461.7,44.6,34.5,12.8,12.6,7.8,7.0,3.0,27.0,38.0
max_temporal_10,252970.0,35672.0,36914.0,103585.0,110423.0,93154.0,56930.0,8550.0,8517.0,26098.0,...,394.3,45.8,38.8,15.0,15.0,75.0,10.0,0.0,3.0,194.1
fairest_relative_10,331870.0,39775.0,40844.0,141403.0,119512.0,91836.0,198835.0,24960.0,24455.0,82951.0,...,469.6,41.7,37.4,12.6,12.3,3.0,5.0,5.0,15.0,65.3

In [82]:
# Concatenate the DataFrames vertically # do this for all
opti_df = pd.concat([opti_df_6, opti_df_10, opti_df_20, opti_df_30, opti_df_40, opti_df_50, opti_df_100, vehicles_ams], axis=0)

In [83]:
opti_df

,A_inhab,A_0_15,A_65+,A_nederlan,A_n_west_m,count,A_inhab_uniq,A_0_15_uniq,A_65+_uniq,A_nederlan_uniq,...,G_woz_woni,dutch_share_pct,non_western_share_pct,young_share_pct,old_share_pct,euclidean_distance,buses_count,trams_count,routes_unique,avg_points_per_cell
max_spatial_6,405385.0,51441.0,50666.0,181266.0,137821.0,52292.0,306580.0,39458.0,39063.0,137193.0,...,468.9,44.8,34.3,12.9,12.7,2.5,5.0,1.0,21.0,24.5
max_temporal_6,131775.0,18581.0,19744.0,51782.0,60119.0,50185.0,37635.0,5367.0,5601.0,15644.0,...,382.6,41.6,43.1,14.3,14.9,87.0,6.0,0.0,3.0,170.7
fairest_relative_6,215725.0,25652.0,27096.0,90535.0,78960.0,50534.0,172605.0,20861.0,21613.0,72319.0,...,470.1,41.9,36.7,12.1,12.5,3.0,4.0,2.0,12.0,41.2
max_spatial_10,587505.0,71715.0,72863.0,261317.0,199562.0,95856.0,354185.0,45384.0,44718.0,158150.0,...,461.7,44.6,34.5,12.8,12.6,7.8,7.0,3.0,27.0,38.0
max_temporal_10,252970.0,35672.0,36914.0,103585.0,110423.0,93154.0,56930.0,8550.0,8517.0,26098.0,...,394.3,45.8,38.8,15.0,15.0,75.0,10.0,0.0,3.0,194.1
fairest_relative_10,331870.0,39775.0,40844.0,141403.0,119512.0,91836.0,198835.0,24960.0,24455.0,82951.0,...,469.6,41.7,37.4,12.6,12.3,3.0,5.0,5.0,15.0,65.3
max_spatial_20,887330.0,107961.0,113089.0,389622.0,306900.0,168706.0,394310.0,51114.0,49773.0,174188.0,...,463.7,44.2,35.1,13.0,12.6,5.7,13.0,7.0,39.0,59.5
max_temporal_20,558070.0,81388.0,83043.0,248786.0,220221.0,202384.0,110825.0,15968.0,15061.0,47534.0,...,389.0,42.9,40.2,14.4,13.6,80.4,20.0,0.0,8.0,214.6
fairest_relative_20,653735.0,80552.0,79009.0,282450.0,232499.0,160241.0,272410.0,35311.0,31841.0,113642.0,...,469.9,41.7,37.5,13.0,11.7,3.1,12.0,8.0,23.0,87.7
max_spatial_30,1299755.0,161697.0,162941.0,559613.0,464616.0,236922.0,401020.0,52021.0,50969.0,177335.0,...,465.9,44.2,35.1,13.0,12.7,3.7,21.0,9.0,45.0,81.7
max_temporal_30,1224435.0,158650.0,161386.0,510016.0,487499.0,276965.0,212570.0,28195.0,27414.0,90656.0,...,397.1,42.6,38.2,13.3,12.9,72.2,30.0,0.0,15.0,169.4
fairest_relative_30,1040080.0,124375.0,128989.0,456337.0,359724.0,248926.0,314050.0,40311.0,38285.0,134857.0,...,469.3,42.9,36.2,12.8,12.2,1.7,18.0,12.0,28.0,115.1
max_spatial_40,1629115.0,206700.0,204956.0,695340.0,596695.0,324836.0,402465.0,52176.0,51106.0,178093.0,...,452.7,44.2,35.0,13.0,12.7,16.6,28.0,12.0,48.0,111.8
max_temporal_40,1859400.0,230418.0,244638.0,787170.0,700787.0,326402.0,260190.0,33648.0,34239.0,114364.0,...,419.3,44.0,35.7,12.9,13.2,50.0,40.0,0.0,19.0,166.5
fairest_relative_40,1369395.0,167884.0,167022.0,597752.0,479689.0,323322.0,333490.0,43454.0,41260.0,143551.0,...,469.2,43.0,36.4,13.0,12.4,1.4,22.0,18.0,30.0,136.7
max_spatial_50,2026995.0,259589.0,253244.0,861890.0,752203.0,409935.0,403100.0,52284.0,51177.0,178485.0,...,445.6,44.3,35.0,13.0,12.7,23.6,35.0,15.0,48.0,140.8
max_temporal_50,2620650.0,329721.0,330333.0,1101801.0,995436.0,401179.0,305440.0,40365.0,38728.0,131857.0,...,417.4,43.2,36.8,13.2,12.7,51.8,50.0,0.0,25.0,179.7
fairest_relative_50,1630305.0,200793.0,196943.0,714595.0,569336.0,391644.0,341445.0,44367.0,42087.0,147530.0,...,468.8,43.2,36.2,13.0,12.3,1.4,27.0,23.0,33.0,162.2
max_spatial_100,3369775.0,420950.0,419060.0,1451698.0,1207541.0,790896.0,403240.0,52298.0,51191.0,178541.0,...,459.6,44.3,35.0,13.0,12.7,9.8,54.0,46.0,51.0,271.3
max_temporal_100,4635185.0,608230.0,573086.0,1912586.0,1810292.0,757990.0,328640.0,43007.0,42147.0,143714.0,...,401.1,43.7,36.0,13.1,12.8,68.1,100.0,0.0,33.0,315.8
fairest_relative_100,3400640.0,417038.0,421130.0,1477286.0,1201149.0,815873.0,374800.0,48601.0,46991.0,165473.0,...,468.3,44.2,35.2,13.0,12.5,1.8,56.0,44.0,39.0,303.1
all_vehicles,8471845.0,1050147.0,1047752.0,3656741.0,3006099.0,2127870.0,403240.0,52298.0,51191.0,178541.0,...,452.319784,44.28,34.99,12.97,12.69,16.98,145.0,133.0,54.0,729.97
Amsterdam,-,-,-,-,-,-,870375.0,122388,112084,382106,...,469.21,43.9,36.26,14.06,12.88,0,-,-,-,-